name: Compile and upload
on: workflow_dispatch

jobs:
  gradle:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Install other dependencies
      run: |
        sudo apt update
        sudo apt install make unzip wget openssl locate

    - name: Cache Android NDK
      id: cache-android-ndk
      uses: actions/cache@v3
      with:
        path: android-ndk-r26-linux.zip
        key: ${{ runner.os }}-android-ndk

    - name: Download Android NDK
      if: steps.cache-android-ndk.outputs.cache-hit != 'true'
      run: wget 'https://dl.google.com/android/repository/android-ndk-r26-linux.zip'

    - name: Setup Android NDK
      run: unzip android-ndk-r26-linux.zip

    - name: Install build-tools
      run: sdkmanager "build-tools;33.0.1"

    - name: Compile the app
      run: |
        make package
        cp android-shim/app/build/outputs/apk/release/app-release-unsigned.apk RCalc.apk
      env:
        ANDROID: 1
        ANDROID_NDK: android-ndk-r26

    - name: Sign the app
      run: |
        openssl rand -base64 16 > ks_pass 
        cat ks_pass ks_pass > ks_creds
        echo -ne '\n\n\n\n\n\nyes\n' >> ks_creds
        keytool -genkey -alias rcalc -keyalg RSA -keystore keystore.jks < ks_creds
        $ANDROID_SDK_ROOT/build-tools/33.0.1/apksigner sign --ks keystore.jks RCalc.apk < ks_pass

    - uses: actions/upload-artifact@v3
      with:
        name: RCalc.apk
        path: RCalc.apk
